import { Lead } from './gemini';

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 555-0101',
    lastContact: '2026-03-27T10:00:00Z',
    status: 'Qualified',
    notes: 'Very interested in the premium plan. Asked about bulk discounts. Needs a follow-up call to finalize pricing.',
    agentId: 'Agent 1',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '+1 555-0102',
    lastContact: '2026-03-25T14:30:00Z',
    status: 'Contacted',
    notes: 'Initial call went well. She is comparing us with competitors. Send case studies.',
    agentId: 'Agent 2',
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'michael@example.com',
    phone: '+1 555-0103',
    lastContact: '2026-03-28T09:15:00Z',
    status: 'Negotiation',
    notes: 'Ready to sign if we can provide a 10% discount. High urgency.',
    agentId: 'Agent 1',
  },
  {
    id: '4',
    name: 'Emily Davis',
    email: 'emily@example.com',
    phone: '+1 555-0104',
    lastContact: '2026-03-20T11:00:00Z',
    status: 'New',
    notes: 'Inbound lead from website. No contact yet.',
    agentId: 'Agent 3',
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david@example.com',
    phone: '+1 555-0105',
    lastContact: '2026-03-26T16:00:00Z',
    status: 'Proposal',
    notes: 'Proposal sent. He mentioned he will review it over the weekend and decide by Monday.',
    agentId: 'Agent 4',
  },
  {
    id: '6',
    name: 'Jessica Taylor',
    email: 'jessica@example.com',
    phone: '+1 555-0106',
    lastContact: '2026-03-27T13:00:00Z',
    status: 'Contacted',
    notes: 'Busy when called. Requested a call back on Saturday morning.',
    agentId: 'Agent 2',
  },
  {
    id: '7',
    name: 'Robert Miller',
    email: 'robert@example.com',
    phone: '+1 555-0107',
    lastContact: '2026-03-24T10:00:00Z',
    status: 'Lost',
    notes: 'Budget too low for our services.',
    agentId: 'Agent 5',
  },
  {
    id: '8',
    name: 'Linda Anderson',
    email: 'linda@example.com',
    phone: '+1 555-0108',
    lastContact: '2026-03-28T08:00:00Z',
    status: 'Qualified',
    notes: 'Decision maker. Wants a demo for the whole team next week.',
    agentId: 'Agent 6',
  },
  {
    id: '9',
    name: 'William Thomas',
    email: 'william@example.com',
    phone: '+1 555-0109',
    lastContact: '2026-03-27T15:45:00Z',
    status: 'Proposal',
    notes: 'Asked for a technical deep dive. Very technical questions.',
    agentId: 'Agent 7',
  }
];
